site_name: ModShardLauncher Modding Documentation
repo_url: https://github.com/DDDDDragon/ModShardLauncher
repo_name: DDDDDragon/ModShardLauncher
edit_uri: edit/master/docs/
copyright: All rights belong to Ink Stains Games. <br> This is a community
  project and is not affiliated with Ink Stains Games.

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

plugins:
    - search
    - table-reader
    - glightbox
    
nav:
  - Index:
    - "Welcome": "index.md"