site_name: ModShardLauncher Modding Documentation
repo_url: https://github.com/DDDDDragon/ModShardLauncher
repo_name: DDDDDragon/ModShardLauncher
edit_uri: edit/main/docs/
use_directory_urls: false
copyright: All rights belong to Ink Stains Games. <br> This is a community
  project and is not affiliated with Ink Stains Games.


theme:
    name: material
    favicon: img/Stoneshard.ico
    features: 
    - navigation.path
    - navigation.top
    - header.autohide
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - content.action.view
    language: en
    locale: en
    palette:
        - scheme: default
          toggle:
            icon: material/brightness-7
            name: Switch to Dark Mode
        - scheme: slate
          toggle:
            icon: material/brightness-4
            name: Switch to Light Mode

extra:
  social:
    - icon: fontawesome/brands/discord 
      link: https://discord.gg/YxfRKYUuht
      name: Stoneshard Mod Hub Discord
    - icon: fontawesome/brands/github
      link: https://github.com/DDDDDragon/ModShardLauncher
      name: GitHub Repository
    - icon: fontawesome/brands/steam
      link: https://store.steampowered.com/app/625960/Stoneshard/
      name: Stoneshard on Steam
    - icon: simple/gogdotcom
      link: https://www.gog.com/game/stoneshard
      name: Stoneshard on GOG

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


plugins:
    - search
    - table-reader
    - glightbox
    - git-authors
    - git-revision-date
    - i18n:
        docs_structure: suffix
        reconfigure_material: true
        reconfigure_search: true
        languages:
          - locale: en
            default: true
            name: English
            build: true
          - locale: zh
            name: 中文
            build: true
            nav_translations:
              Index: 首页
              Welcome: 欢迎
              Guides: 指南
              Introduction: 简介
              Creating your First Mod: 开始
              Installing Mods: 如何使用MOD
              API: API
#           You can remove the nav_translations above and remove comments here if you want to have custom ZH nav.
#           This would avoid setting up empty 'TODO' pages.
#           nav:
#             - 首页: "index.md"
#             - 指南:
#               - "简介": "guides/introduction.md"
#               - ... : ...
          

nav:
  - Index:
      - "Welcome": "index.md"
  - Guides:
      - "Introduction": "guides/introduction.md"
      - "Creating your First Mod": "guides/start-modding.md"
      - "Installing Mods": "guides/how-to-play-mod.md"
      - "API": "guides/api.md"
