name: ci
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
    paths:
      - 'docs/**'
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material mkdocs-table-reader-plugin mkdocs-glightbox mkdocs-static-i18n[material] mkdocs-git-authors-plugin mkdocs-git-revision-date-plugin
      - run: mkdocs gh-deploy --force
